### ISSUE TITLE
Feature Request: Include Kitsune Spell Familiarity and simiilar

### ISSUE THREAD

**Issue by sorrythatuserbla** [reonZ/pf2e-dailies#11]
I don't know if this fits the scope of this module but there are several feats which allow the use of different spells each day like Kitsune Spell Familiarity which could be included. 
It reads like: "_During your daily preparations, choose Daze, Forbidding Ward, or Ghost Sound. Until your next daily preparations, you can cast this cantrip as a divine innate spell at will._" 
If it's not in the scope of this module just close the issue and keep up the great work!

<3 your module!

**Comment by MrVauxs** [comment]
As far as I've seen Spells were not covered because you can just, make a new spell entry.
What you described is just preparing cantrips. You can do that in Foundry already.

**Comment by reonZ** [comment]
Well i have done `Trickster's Ace` which offer a spell each day as well.
But here, since you only have the choice out of 3 spells, it is no different than any prepared spell you would do normally.
All prepared spells are daily.
