### ISSUE TITLE
Coffee cup icon not appearing

### ISSUE THREAD

**Issue by rockwallguy** [reonZ/pf2e-dailies#12]
I'm in a new world with only your mod active.  None of my PC character sheets are getting the little coffee cup symbol.  

I have version 1.18.1 of PF2e dailies.  The rest of my info is in the screenshot below.  I'm self-hosting on the native app. 

Any ideas?

![image](https://user-images.githubusercontent.com/79724010/219281262-0e8e3c8f-2d96-4a8c-8174-d9a36ec96ad9.png)
![image](https://user-images.githubusercontent.com/79724010/219281569-0f3f1ef7-aef6-4c24-888c-5a3c9dfde0e2.png)

**Comment by reonZ** [comment]
```This module will provide a convenient interface to handle a character's daily preparations if they have at least one of the following feats, items or features```
