### ISSUE TITLE
Search dailies error out when opening the Compendium browser

### ISSUE THREAD

**Issue by Cerapter** [reonZ/pf2e-dailies#15]
Metamagical experimentation, for example.

```
Uncaught (in promise) Error: PF2e System | Tried to pass an initial filter to uninitialized tab "feat"
    ErrorPF2e main.bundle.js:19
    open main.bundle.js:1
    openTab main.bundle.js:1
    #n interface.ts:293
```

The issue is in `DailiesInterface.#onSearch()`, probably caused by the Compendium Browser refactor at https://github.com/foundryvtt/pf2e/pull/6833 .

**Comment by reonZ** [comment]
This was a pain but it should be working now with version `2.4.0`
