### ISSUE TITLE
Temp Scrolls can't be co-existing with temp potions or other daily crafting items

### ISSUE THREAD

**Issue by sakusenerio** [reonZ/pf2e-dailies#16]
For example, I have a character who can have daily scrolls and some daily temp potions or talismans(for instance a Thaumaturge with scroll thaumaturgy & talisman esoterica feat), and then I make temp scrolls using the MOD, everything is fine by now. After that I make daily talismans using system crafting tab...temp talismans are added, but temp scrolls disapeared. 
If I do daily crafting using system craft tab, then use the MOD to generate daily scrolls, then earlier items would disapear on that as well.

It will be nice to have them co-existing...

**Comment by reonZ** [comment]
![image](https://user-images.githubusercontent.com/651462/225440244-d6f0e041-1845-4f78-bcb2-969fbc442a61.png)

I have no idea what your issue is, but the module doesn't interfere with the talismans, all i did was both use the `Complete Daily Crafting` in the crafting tab and then click on the module icon to do my daily preparations.

**Comment by sakusenerio** [comment]
> 

hmmmm, thanks for the reply! Guess there's a conflict of mods...I'll check again.

**Comment by reonZ** [comment]
Temporary items are not even managed by the module (the module doesn't delete them), they are automatically removed by the system when you use the `Rest for the Night` action.

**Comment by reonZ** [comment]
Let me know what you find out please, maybe i can do something about it.

**Comment by reonZ** [comment]
Oh actually, the `Complete Daily Crafting` seem to remove all temporary items before crafting new ones, so if you use it after using the module, then the items disappear, i dunno if it is a new behavior or not.

**Comment by sakusenerio** [comment]
> 

I found it out too, `daily crafting` first, `coffee icon` second - everything works perfect. Otherwise scrolls will be deleted by system's `complete daily crafting`.
It's a little weired but I can work with that, just need to keep it in mind to do crafting first.

**Comment by reonZ** [comment]
Yeah, i looked at the code in the system for `Complete Daily Crafting`  and it deletes all temporary items before crafting, so you have to use it first, i am gonna ask one of the dev if something can be done about it.

**Comment by sakusenerio** [comment]
Ok, thanks!

**Comment by reonZ** [comment]
With version `2.5.0`, i prevent the system from deleting temporary items when using `Complete Daily Crafting`, so you won't have to care about the order or operations anymore.

*NOTE: the module now requires the dependency module libwrapper to make the new feature possible*
