### ISSUE TITLE
Combat Flexibility errors

### ISSUE THREAD

**Issue by Sorellia** [reonZ/pf2e-dailies#18]
Combat Flexibility is producing errors when trying to open the compendium with the magnifier glass, and trying to manually drag in a feat that qualifies for the feature produces another error.

The error for trying to open the compendium with the magnifier:

```
Uncaught (in promise) TypeError: undefined. Cannot set properties of undefined (setting 'selected')
[Detected 1 package: pf2e-dailies]
    at Re (shared.ts:36:14)
    at Ne (shared.ts:81:5)
    at async DailiesInterface.Ee (shared.ts:26:9)
```

And for trying to drag in a feat manually:

```
Uncaught (in promise) TypeError: undefined. Cannot read properties of undefined (reading 'class')
[Detected 1 package: pf2e-dailies]
    at drop.ts:148:70
    at Array.map (<anonymous>)
    at We (drop.ts:148:28)
    at DailiesInterface.Me (drop.ts:20:52)
    at DailiesInterface._onDrop (interface.ts:258:52)
```

Due to this, on any fighter character that is level 9 or higher, completing daily prep is impossible as the module does not allow me to leave combat flexibility's field empty.

This has been tested on a fresh world with just this module (and its prerequisite) activated, with both it and the Pathfinder 2e system updated to their newest versions, and is present in those circumstances as well as my normal game worlds.

**Comment by reonZ** [comment]
The system changed once again the way feat filters work, version `2.6.0` should now fix the issue.
