### ISSUE TITLE
Feature Request: Reminders for Spell Preperation and daily crafting

### ISSUE THREAD

**Issue by trapbuilder2** [reonZ/pf2e-dailies#22]
I think it would be really handy if the dailies window could reminder prepared spellcasters to choose their spells and alchemists to choose their daily crafting. Even if they don't _do_ anything, a reminder would be handy

**Comment by reonZ** [comment]
The module doesn't have anything like that, every daily requires a choice to be made.

Also, this is something that shouldn't require any reminder, spell casters should know that they can switch their spells and just the fact of using `rest` or `daily preparation` should be enough of a reminder in itself.
