### ISSUE TITLE
Unregistered game setting?

### ISSUE THREAD

**Issue by weepingminotaur** [reonZ/pf2e-dailies#29]
Saw this console error last night during a game session. Seems to relate to PF2e Dailies.
<img width="597" alt="Screenshot 2023-10-04 at 10 32 44 PM" src="https://github.com/reonZ/pf2e-dailies/assets/90105219/f810d292-4416-45df-bef8-95d7601cdecd">

**Comment by reonZ** [comment]
while the first error seem related to this module, the others aren't.

i just logged in with `PF2e Dailies` active and don't get any error, maybe some conflict with another module.

**Comment by weepingminotaur** [comment]
Cool. I will see if I get that error again and try to figure out what module is conflicting.

**Comment by reonZ** [comment]
the error also seem quite alarming to me, because it says that it can't find `CONFIG.PF2E` in your global, which shouldn't be possible considering this is something used and put there by the pf2e system itself

**Comment by weepingminotaur** [comment]
Yep, and I haven't messed with my config files at all (I never do). Anyway, I haven't gotten these errors since posting, which is good. Will keep an eye open in case anything else crops up.

**Comment by reonZ** [comment]
ok, don't hesitate to re-open this if needed
