### ISSUE TITLE
Feature Request: Daily Spell Casting

### ISSUE THREAD

**Issue by avsamano** [reonZ/pf2e-dailies#30]
Not sure if this is the right place to make a request...
So I apologize if this is improper.

I'd like to use this module for spells that my character casts every morning.
IE - Pocket Library and Mind of Menace.

I tried to create a custom Daily for this, but couldn't make it work.
Is this possible and I'm just doing it wrong?
Or would this require a new feature?

Thank you!

**Comment by reonZ** [comment]
while this is not what the module is supposed to do, you could definitely cook up some kind of reminder for them

the first issue with what you want to do is that the module offers players choices for their dailies, here you want something that requires no choice, but you can cheat and simply provide a 1 choice select menu for them

the other issue is that you need an `item` to link your choices but you can just link a random `item` that your character has (feat is probably the best)

the last problem and not the least is that you can't cast a spell from a chat link, which means that you will have to cast the spell in the daily process, which can be tricky depending on your spellcasting entries, if you have more than one prepared, if it has already been expended, etc..

i have worked with spells on some of my modules and this can become quite complicated

so you can do it, but it will require you to go the extra mile and work on it, i can link you some code i use on one of my modules, see if you can make head or tail of it, i can help you along the way but this is not something i want to tackle entirely sorry :p

https://github.com/reonZ/pf2e-toolbelt/blob/master/src/features/summary.js#L195
https://github.com/reonZ/pf2e-toolbelt/blob/master/src/features/summary.js#L130

you can ofc hardcode most of it if you want and are sure nothing will change (spell rank, etc..) which would make things way easier than creating something dynamic

if you decide to try your luck, you can always contact me on the pf2e foundry discord, i even have a channel for `PF2e Dailies` there

**Comment by avsamano** [comment]
Ok, I'll check out your code examples and see what I can figure out.
Thank you so much!
