### ISSUE TITLE
Feature Request - Staff Nexus support when Preparing a Staff

### ISSUE THREAD

**Issue by Unoblueboy** [reonZ/pf2e-dailies#35]
Would it be possible to add support the Wizard's Staff Nexus in 2 ways:

1. Allow for additional Spell Slots to be used to charge the staff at 8th and 16th level
2. Have a way to mark a stave as your makeshift staff so that when you prepare it you don't automatically gain a number of charges equal to the rank of your highest spell slot.

**Comment by reonZ** [comment]
this was added with the `2.16.0`

**Comment by dodgepong** [comment]
Hoping I'm not driving myself crazy here. Does this still work? I can add, say, a Staff of Air to a character sheet and I get the Prepare a Staff prompt when I click the Dailies, but how can I Prepare a Staff for a Makeshift Staff? I feel like I am fully missing something simple.

**Comment by reonZ** [comment]
a makeshift staff is the same as any staff, just one you made yourself

**Comment by dodgepong** [comment]
Right, sure, but I don't get a Prepare a Staff prompt when clicking the Dailies button for a Staff Nexus staff. I have a Charges Spellcasting entry set up for the staff (though it appears in the Known Spells section, not the Activations section). Is there a staff I have to add to my inventory other than the regular vanilla Staff in order to tell the system that I have a staff I'm able to prepare?

Apologies if this is a dumb question, I still feel like I'm missing something silly.

**Comment by reonZ** [comment]
You don't need a `charges` spellcasting entry for your staff, if you have one, remove it.

There is nothing special to do, you need a staff with spells in its description like any other staff and it will be listed with other staves during daily preparation.

**Comment by dodgepong** [comment]
> There is nothing special to do, you need a staff with spells in its description like any other staff and it will be listed with other staves during daily preparation.

Okay, I did not realize that just literally adding a spell to a staff's description box (dragging it from the compendium into the description text box to have a UUID reference) made it a magical staff, that seems wildly unintuitive. I think I have it figured out now though. Thanks!

**Comment by reonZ** [comment]
> that seems wildly unintuitive

The reason this feature exists on this module is to handle something that isn't handled by the system, we do what we can with what we have, if staves had a proper UI/handling by the system, this wouldn't need to exist in the first place.

**Comment by dodgepong** [comment]
Yeah, sorry, that was a comment directed at the PF2e system, not this module. Thanks for your work!
