### ISSUE TITLE
Feature Request: Summoner Feats Flexible Transmorgification and True Transmorgification

### ISSUE THREAD

**Issue by LebombJames** [reonZ/pf2e-dailies#36]
https://2e.aonprd.com/Feats.aspx?ID=2928
https://2e.aonprd.com/Feats.aspx?ID=2941
Both feats allow Summoners to choose/swap evolution feats per day.

**Comment by reonZ** [comment]
There is no way to do that, those feats are on the summoner while their mechanic swap/add feats on the eidolon which is a another character that is not linked to the summoner in any way.
