### ISSUE TITLE
Feature Request / QoL - Option to have staff spells at bottom of spell list

### ISSUE THREAD

**Issue by maplealmond** [reonZ/pf2e-dailies#38]
Staff-generated spells from this module appear at the top of the spellcasting list.  They can be moved, but will need to be moved each preparation if the user typically kept them at the bottom.

Would appreciate if this was a user setting.

**Comment by reonZ** [comment]
this was added with the `2.16.0`

**Comment by maplealmond** [comment]
Very nice.  Thank you.
