### ISSUE TITLE
Mind Smith Archetype

### ISSUE THREAD

**Issue by MrVauxs** [reonZ/pf2e-dailies#4]
It may very well be something of a legendary feature request, but you asked for any possible dailies, so, here is a bunch:
- [x] [Mind Smith Dedication](https://pf2etools.com/feats.html#mind%20smith%20dedication_da)'s daily weapon of choice
- [x] [Mental Forge](https://pf2etools.com/feats.html#mental%20forge_da)'s modifications to the above daily weapon
- [x] [Malleable Mental Forge](https://pf2etools.com/feats.html#malleable%20mental%20forge_da) is an upgrade of the above
- [x] [Runic Mind Smithing](https://pf2etools.com/feats.html#runic%20mind%20smithing_da) daily runes to the above weapon
- [x] [Advanced Runic Mind-Smithing](https://pf2etools.com/feats.html#advanced%20runic%20mind-smithing_da) upgrade to the above
- [ ] [Metallic Envisionment](https://pf2etools.com/feats.html#metallic%20envisionment_da) not really a daily, but modifies the above weapon

Feel free to shoot this down, this is ridiculous enough to warrant it's own module

**Comment by reonZ** [comment]
done with `1.16.0` except the last one, this should be done with a RE.
