### ISSUE TITLE
Staves don't auto-add spells

### ISSUE THREAD

**Issue by fishrobe** [reonZ/pf2e-dailies#42]
I get a pop up that this module now handles staves, and I need to disable PF2E Staves, but without PF2E staves enabled, I don't get the staff entries automatically added to my spell list.

**Comment by fishrobe** [comment]
Can I ask why I get the pop up that Staves needs to be disabled if the one thing it does isn't actually planned to be done by pf2e dailies? Staves seems to work with this active, and Dailies does a ton of things I like.

**Comment by reonZ** [comment]
this module handle staves and therefore is in conflict with `PF2e Staves`

**Comment by fishrobe** [comment]
I see. I guess I just don't understand how this module handles spells from
staves, since it doesn't add them, and it apparently isn't an intended
feature.

So I guess my question is, how does this module handle spells from staves
if it doesn't add them to the character's spell list? I feel like I'm
missing something.

**Comment by reonZ** [comment]
Why do you keep repeating " it apparently isn't an intended feature" ? it is in the module and has been for a few version now.

The module handles staves as advertised...
