### ISSUE TITLE
Feature request: Support "Expert Longevity"

### ISSUE THREAD

**Issue by Michael-B-23** [reonZ/pf2e-dailies#44]
Requesting support for ""Expert Longevity""
https://2e.aonprd.com/Feats.aspx?ID=22

Basically lets you choose a skill to go from trained to expert when you rest. You already support "[Ancestral Longevity](https://2e.aonprd.com/Feats.aspx?ID=12)" 

Thank you for your consideration.

**Comment by reonZ** [comment]
This will be supported in the next update, waiting for the `5.13.0` to come out.
