### ISSUE TITLE
Ageless Spirit countering built-in implementation

### ISSUE THREAD

**Issue by steev42** [reonZ/pf2e-dailies#45]
The Ageless Spirit ancestry feat for Leshies has a built-in implementation via a Roll Option in the actions tab. The Dailies implementation doesn't take that into account, treats it as an additional existing trained skill, and forces you to select a different skill.

The Dailies implementation should either list every skill (with their current level of training), or read which roll option is selected and show that as well.

**Comment by reonZ** [comment]
I have found out about that today and already put in place something in the module for that, the module will delete the rule elements added by the system in the feats so they don't conflict with the daily preparation.

It is actually worse than that, the system roll options already set a skill to trained and the module add an extra one.
