### ISSUE TITLE
Bug when preparing a stave

### ISSUE THREAD

**Issue by TiloBuechsenschuss** [reonZ/pf2e-dailies#47]
We've recently rebuilt our party's witch. Now they can't prepare a staff. They always get the following error: 
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'system')
    at returnedEntry (spellcasting.js:206:53)
    at getBestSpellcastingEntry (spellcasting.js:230:9)
    at getBestSpellcastingEntryForStaves (staves.js:121:20)
    at je.processData (process.js:202:23)
    at async #c (interface.js:506:3)
```
Other casters still can prepare, so maybe it's only this actor?

[fvtt-Actor-boreas-hellborus-FRJfb8OoOb8Qn5Jg.json](https://github.com/reonZ/pf2e-dailies/files/14225091/fvtt-Actor-boreas-hellborus-FRJfb8OoOb8Qn5Jg.json)

**Comment by reonZ** [comment]
Both your prepared spellcasting entries were empty, this it what caused the crash, i made sure it won't happen anymore.

Your staff is a pre-remaster one and has a spell that no longer exist in the system, this would have crashed the daily preparation as well, and i also made sure this will be the case after this patch.

**Comment by TiloBuechsenschuss** [comment]
Great, thanks a bunch. :-)
