### ISSUE TITLE
Feature Request: Support Homebrew Staff

### ISSUE THREAD

**Issue by jocolamarco** [reonZ/pf2e-dailies#49]
If i create a magic staff with my own selection of spells, how can make this be picked up during daily preparations to add the spellcasting entries?

**Comment by reonZ** [comment]
There is no "homebrew" staff, you just have to reproduce how staves are made in the system.

**Comment by jocolamarco** [comment]
Hi @reonZ ,

That's what I did. The staff shows up in the screen of the daily prep but it doesn't create the entry in the spells list.

**Comment by reonZ** [comment]
It's easier to simply use one from the system and change what is needed directly in the html
