### ISSUE TITLE
Requesting support for Spellhearts

### ISSUE THREAD

**Issue by ForbiddenZex** [reonZ/pf2e-dailies#50]
Hi, I was wondering if it would be possible to add spellheat support to this module. A PC could have some in inventory and you could prepare the one you want then the spells would be added to the PC's spell list.

**Comment by reonZ** [comment]
This would require quite a lot of work, maybe even more than handling the staves, and there is the issue of tracking 1 spellheart per item that makes it very tricky.
Also, the system is slowly implementing attachments right now, so if i were to tackle this task, i would at the very least wait for it to be done in the system.
