### ISSUE TITLE
[Request] Expanded options for daily ration usage

### ISSUE THREAD

**Issue by weepingminotaur** [reonZ/pf2e-dailies#51]
If the party is in town, I don't want them consuming rations from their inventory when they would realistically go to the nearest inn and get a hot meal. :)

It would be nice if Dailies could give users a choice of either consuming a ration or a message telling them to "go get a hot meal in town!" (or some other text that reflects where they are).

**Comment by reonZ** [comment]
They don't have to consume rations, by default, the option is always set to "do not consume", so i don't see the issue. They can say whatever they want when they do their preparation, this isn't a narrative module.

**Comment by weepingminotaur** [comment]
Wasn't asking for narrative, just some text reminding them that they could get a meal in town, but hey, whatever.

**Comment by reonZ** [comment]
That seems super arbitrary though and not really in line with what the module does.
