### ISSUE TITLE
[Feature Request] Option to specify staff spotaneous slot usage

### ISSUE THREAD

**Issue by this-gavagai** [reonZ/pf2e-dailies#52]
Thanks for this great module!

At present, when casting a spell from a staff as a spontaenous caster, a Dialog pops up asking if the caster wants to use spontaneous spell slots to decrease the charges used.

Would you ever consider allowing this choice to be passed in code via the args variable being read here:
https://github.com/reonZ/pf2e-dailies/blob/6e4ca89af5134b54cb729c64cbf9a3c3f7959da7/src/spellcasting.js#L6

My use case is that I'm trying to provide an alternate interface for in-person games, but the dialog is not accessible with Monk's Common Display.

**Comment by reonZ** [comment]
How would you pass which spellcasting entry you want to use ?

**Comment by this-gavagai** [comment]
Just by passing an` Id`, I'd think, though there might be other approaches. I've shared a PR outlining what I had in mind.

**Comment by reonZ** [comment]
i guess this is doable, i may implement something like that

**Comment by reonZ** [comment]
With the version `3.0.0` of dailies, you able to provide it, a new 
```js
spontaneous?: { entryId: string; rank?: OneToFour }
```
option has been added, although, everything changed in the module, staves now have their own spellcasting entry type `StaffSpellcasting`
