### ISSUE TITLE
[Bug] Unable to pull the Staff spellcasting entry

### ISSUE THREAD

**Issue by LiyuNodream** [reonZ/pf2e-dailies#55]
VTT V11.315
pf2 v5.15.0
mod v2.24.0
————————————
If I only active this mod, when I draw a staff into character's bag, it can't create spellcasting entry automatically.
But if I active the old [pf2e staves] mod too, it's weird that the staves mod can automatically create the entry.
I'm not sure why (I've already exclude the interference from other modules), can you fix it ? Thanks.

**Comment by reonZ** [comment]
this is a module about daily preparations, you need to prepare your staff during them, like everything else
