### ISSUE TITLE
API For Custom Dailies

### ISSUE THREAD

**Issue by Axel-of-the-Key** [reonZ/pf2e-dailies#58]
There is no mention here for the structure for custom dailies. I am attempting to create one along the lines of other choice-based daily preparations with my homebrew, but am unsure what each field requires as there is no tutorial on how to use it that I can locate.

**Comment by reonZ** [comment]
All the built-in dailies are made using the same method you would create a custom daily ,so just go and look at the source code.
https://github.com/reonZ/pf2e-dailies/tree/master/src/data
