### ISSUE TITLE
Familiar abilities sort order

### ISSUE THREAD

**Issue by Suldrun45** [reonZ/pf2e-dailies#59]
The order of the items in the Familiar Abilities dropdowns seems to be based on the order of their UUID, which makes it quite hard to find the one you want.
Could it be possible to sort them in alphabetical order of their names?
![image](https://github.com/reonZ/pf2e-dailies/assets/49712710/4d4e4740-5871-4796-9961-f63371699d50)

**Comment by reonZ** [comment]
Right, i knew i forgot something, it was on the todo list
