### ISSUE TITLE
Flexible Transmogrification

### ISSUE THREAD

**Issue by MrVauxs** [reonZ/pf2e-dailies#6]
[Flexible Transmogrification](https://pf2etools.com/feats.html#flexible%20transmogrification_som)
![image](https://user-images.githubusercontent.com/32039708/217964481-bc806bbb-37aa-407f-ba7f-22432908a8ea.png)

**Comment by MrVauxs** [comment]
This will likely require adding a way of saying that an Eidolon sheet belongs to a character on which the dailies are done on.
Familiars have it easier as that is already implemented on their sheets.

**Comment by reonZ** [comment]
Sadly, without support from the system itself, this goes beyond the scope of the module.
