### ISSUE TITLE
Broken on FoundryServer.com servers

### ISSUE THREAD

**Issue by GeorgeWL** [reonZ/pf2e-dailies#60]
This is caused by FoundryServer only updating on Minor version releases, and usually ignoring patch versions.

Should be a simple fix, changing the required version from the exact version of 15.5.1 to 15.5.x, as by semver rules, unless the patch fixes a breaking bug of your integration, patch versions should be ignored.

**Comment by GeorgeWL** [comment]
https://github.com/reonZ/pf2e-dailies/pull/61

**Comment by reonZ** [comment]
Firstly, i don't really understand what your issue is, are you telling me that you can't download system fixes ?
Secondly, the reason i changed the required system version is because i use something that was changed in it.
So, i can't comply to your request even if i wanted to.

**Comment by GeorgeWL** [comment]
see that's fair, honestly I'm too used to other folks updating for no good reason

FoundryServer is managed hosting, so the updates are handled by the folks who run that, and disabled for users
