### ISSUE TITLE
Multiclassed Wizard/Cleric staff defaults to incorrect tradition when doing dailies

### ISSUE THREAD

**Issue by nonegoodleft** [reonZ/pf2e-dailies#62]
When preparing a staff as a Wizard that is multiclassed as a Cleric, the preparation defaults to Divine Spell Attack/DCs (or really any other tradition other than Arcane) whenever the Key Attribute is set to anything other than Intelligence.

So, for example, I have a prepared spellcasting entry with Proficiency set to "Spell Attack Modifiers and DCs," Tradition set to "Arcane," and its Key Attribute set to" Intelligence," as you would for any Wizard.

Next I have another prepared spellcasting entry with Proficiency set to "Spell Attack Modifiers and DCs," Tradition set to "Divine," and its Key Attribute set to" Wisdom." When I do my dailies, the staff I have is prepared as "Divine" with the Attack and DCs to match.

Further, if I change the Divine prepared entry to any tradition besides Arcana, the staff is prepared as that tradition. If I change the Key Attribute to any attribute other than Intelligence it prepares the staff as whatever the tradition is set to. The only way to have the staff prepared as Arcane is to have both entries set to Intelligence. If both are set to Intelligence, it doesn't matter what tradition the "divine" entry is set to, the staff will be prepared as Arcana as it should.

It seems as though all spellcasting attributes take precedence over Intelligence when preparing a staff. Perhaps a simple selector on the staff entry for which tradition it should be prepared as would be helpful?

Thanks

**Comment by reonZ** [comment]
The module is supposed to look for the entry with the best modifier and if more than one is found, use the one that has an attribute matching your key attribute, so if it doesn't do that, then it means something is wrong.

**Comment by reonZ** [comment]
it should be resolved with version `3.1.4`
