### ISSUE TITLE
FVTT - Update to 3.2.0

### ISSUE THREAD

**Issue by myzar472** [reonZ/pf2e-dailies#63]
Unable to update/install.

Error is:
uncaught (in promise) Error: Unable to load valid module manifest data from "https://github.com/reonZ/pf2e-dailies/blob/master/package.json"
Error parsing module manifest data from https://github.com/reonZ/pf2e-dailies/blob/master/package.json: Unexpected token '<', "

**Comment by reonZ** [comment]
That error makes no sense, `package.json` isn't a module manifest and has nothing to do with the module itself.

Also `3.2.0` is a v12 update, so unless you are testing v12, this update isn't for you.

**Comment by reonZ** [comment]
This is because foundry isn't smart enough to recognize that you aren't using a v12 version when it comes to considering this update and yet tells you that it can't update the module because you aren't v12 compatible.
Ironic but problematic in this case.
