### ISSUE TITLE
Cannot Update to 3.1.5

### ISSUE THREAD

**Issue by avagdumortesin** [reonZ/pf2e-dailies#64]
Trying to update PF2e Dailies from 3.1.4 to 3.1.5 fails with a "SETUP.PackageUpdateCoreundefined" error.
This is using the Electron app on Windows 11 with FoundryVTT version 11.315.

This might be due to some issues with the 3.2 beta release and/or the `module.json` files in both of these. I'm not sure whether the 3.1.5 `module.json` file needs to have a `"maximum": "11"` added to the `compatibility` section starting at line 15, or if the PF2E relationship needs a `"maximum": "5.15.3"` value.

Obviously, I can update manually, but it would be ideal to have the automatic updater work.

**Comment by avagdumortesin** [comment]
Actually, I lied; I can't update manually because it has the same manifest URI.

**Comment by fishrobe** [comment]
Same problem with multiple modules (Interactive Token Tooltips and Toolbelt are doing it too). I am wondering if this update is only for the v12 beta, and that's why,  but I don't know.
