### ISSUE TITLE
Daily Preperation Error

### ISSUE THREAD

**Issue by CinderKing1214** [reonZ/pf2e-dailies#65]
I keep getting this error saying:
The daily selections avesd on this character were not compatible with the current version of the module and have been reser. 3.0.0.
You can now filter out dailies on a per-character basis, the option is directly available in thre header of the prearation window (The orginal setting has been removed).
You will now find your prepared staff in the ACtiovations tab of the character sheet.

The odd thing is that it works prefectly fine for another sheet but the rest do not work.

I'm on Foundry VTT Version 11 Stable, Build 315. Pathfinder Second Edition 5.15.3.

Am I doing something wrong?

**Comment by reonZ** [comment]
That is not an error, it is a message warning you that previous data isn't compatible with the current version and was wiped.

Just do your daily as usual.

**Comment by CinderKing1214** [comment]
Gotcha, thanks!
