### ISSUE TITLE
Familiar Skilled can only be selected once. 

### ISSUE THREAD

**Issue by Linguz** [reonZ/pf2e-dailies#66]
![image](https://github.com/reonZ/pf2e-dailies/assets/26839279/b96bcf64-fbbd-4e07-898d-65560b1da153)

Skilled is (I believe) the only familiar ability that can be selected more than once. I have my familiar set to be Skilled for all magic knowledge skills but cannot choose it more than once.

**Comment by reonZ** [comment]
this is annoying, the whole feature was a nightmare to put in place.

note that any fix will only be available for the v12 version.

**Comment by reonZ** [comment]
I have made it possible to select it multiple times, though like i said above, this is only for v12.
