### ISSUE TITLE
Familiar Abilities Resetting

### ISSUE THREAD

**Issue by Linguz** [reonZ/pf2e-dailies#67]
Familiar abilities reset every long rest. Would it be possible to have the default remember what was last selected like Quick Study does?

**Comment by reonZ** [comment]
Are you in v12 ? I found the issue but as far as i can see, it was introduced with the latest version of the module which is on v12.

Tell me if i am wrong.

**Comment by reonZ** [comment]
This was fixed in `3.2.1` for v12 only.
