### ISSUE TITLE
[Feature Request] Blazons of Shared Power

### ISSUE THREAD

**Issue by K9GM3** [reonZ/pf2e-dailies#71]
[Blazons of Shared Power](https://2e.aonprd.com/Equipment.aspx?ID=1221) are attuned to two specific items when invested, copying the runes from one to the other. Is this something that this module could automate?

**Comment by reonZ** [comment]
I imagine it could though probably not easy, but this is out of the scope of the module itself as this is not a daily mechanic, so i would not implement it as one of the built-ins.

You would have to make it a custom daily if you wanted to automate it for your world.
