### ISSUE TITLE
Add spells from Kineticist Gate attenuators 

### ISSUE THREAD

**Issue by hostlund** [reonZ/pf2e-dailies#72]
Gate attenuators gives Kineticist a spell based on the element. Different spells based on the level of the Gate, there is total 3 levels. Is it possible to add those spells to the activations tab?

The picture have the first Gate attenuator
<img width="572" alt="Skärmavbild 2024-07-11 kl  10 53 50" src="https://github.com/reonZ/pf2e-dailies/assets/459391/f4d3a926-a410-4760-ad74-7aef14519645">

**Comment by reonZ** [comment]
Those aren't part of the daily preparation.

**Comment by hostlund** [comment]
No, it would probably make more sens to have it in PF2 Staves. But that module seems to be discontinued and/or merged with this.
