### ISSUE TITLE
Config Menu not saving changes.

### ISSUE THREAD

**Issue by TiltedWatcher** [reonZ/pf2e-dailies#73]
Experiencing the same issue that was mentioned in this issue (commented there as well.):
https://github.com/reonZ/pf2e-dailies/issues/70#issuecomment-2254636566_

The config menu doesn't save any changes made, defaulting to everything being active after closing it.

![2024-07-28_22-29-12 1](https://github.com/user-attachments/assets/13a321da-5c24-4240-b07a-19c3a94c84df)

That's on Foundry v11.315, using Pathfinder 2nd Edition v5.16.1, hosting the game on ForgeVTT.

**Comment by reonZ** [comment]
V11 is long forgotten, i can't help you.
