### ISSUE TITLE
[Feature Request] Option to notify when characters do NOT consume rations

### ISSUE THREAD

**Issue by Chainlinc3** [reonZ/pf2e-dailies#74]
This isn't exactly critical by any means-- Not every campaign is going to even bother with ration tracking.  The default is great and positively declares when characters use a ration, but I was wondering if the inverse was possible-- Could we have a toggle in the settings to add a notice whenever someone does their dailies WITHOUT using a ration?

It would be a great reminder for people (like me) who are getting ready to do a survival campaign, and don't want to deal with "Oops, I ran out of rations five months ago and never thought to check, tee-hee".

**Comment by reonZ** [comment]
I don't see how the lack of positive message difers from a negative message, if the players aren't the ones keeping track of rations themselves then the GM does it and will check on the top of the daily message the same way in both case.
