### ISSUE TITLE
Champion's Blessed Armament missing options

### ISSUE THREAD

**Issue by ffanxii4ever** [reonZ/pf2e-dailies#75]
I've updated both the Pathfinder 2e system and Pf2e Dailies to the latest release, and a Champion PC with Blessed Armament can only choose between Returning and Shifting, missing the Fearsome, Vitalizing, and Ghost Touch options.   It was working prior to the v12 and PC2 releases.

![image](https://github.com/user-attachments/assets/57a44847-b70c-425c-b086-e0c71cfd672e)

**Comment by reonZ** [comment]
I was waiting for somebody to complain about it before i start working on it.

**Comment by reonZ** [comment]
Though, the way you can respec the runes with a 10 min rest or an action with `Armament Paragon`, it is probably best not to use this daily at that point.
