### ISSUE TITLE
[Feature Reqest] apply or integrate the fatigued condition to characters automatically

### ISSUE THREAD

**Issue by bubakarz88** [reonZ/pf2e-dailies#76]
Good day. I am not sure if you all do feature requests, but there used to be a mod called pf2e fatigue (https://foundryvtt.com/packages/pf2e-fatigue/https://foundryvtt.com/packages/pf2e-fatigue/) but it appears to have been abandoned and not updated. Would it be possible to have something like this added, just to make keeping track of time easier.

Thank you.

**Comment by reonZ** [comment]
Not sure what that entail or what you expect, but "keeping track of time" isn't something this module does, it just let you select stuff you normally do during daily preparation.

**Comment by bubakarz88** [comment]
> Not sure what that entail or what you expect, but "keeping track of time" isn't something this module does, it just let you select stuff you normally do during daily preparation.

Alright. I was just asking.
