### ISSUE TITLE
Issue with Crown of the Companion

### ISSUE THREAD

**Issue by bucket-au** [reonZ/pf2e-dailies#77]
Hi,
    Firstly. Great mod!

Second, having a small issue with it.

One of my players has a [Crown of the Companion](https://github.com/foundryvtt/pf2e/blob/0fbad80cf4c00c14643ed8476ec0c2515805bf5d/packs/equipment/crown-of-the-companion.json) and when they invest it, Dailies stops working for them.  I have a feeling the issue might actually be with the Crown itself from the PF2E system, but have (quickly) hit my limits to debug. :(

I scanned over the code and couldn't see any discrepancies.

### Error from the Console (when clicking the coffee cup):

VM1677:10  Uncaught (in promise) TypeError: undefined. Cannot read properties of undefined (reading 'name')
[Detected 1 package: pf2e-dailies(3.6.1)]
    at Object.label (eval at ss (dailies.ts:138:20), <anonymous>:10:41)
    at interface.ts:320:39
    at Array.map (<anonymous>)
    at Cr._prepareContext (interface.ts:315:21)
    at async #render (foundry-esm.js:44319:23)
    at async Semaphore._try (foundry-esm.js:6645:19)

### Debugger link displays(with a red X after items.item.name,):

(async function anonymous(utils,createDaily,createComboSkillDaily,createLoreSkillDaily,createLanguageDaily,createResistanceDaily,createScrollChainDaily
) {
return {
    key: "stMkaThHajt4qhNg",
    items: [{
            slug: "crown-of-the-companion",
    uuid: "Compendium.pf2e.equipment-srd.Item.3jd8wUCHH5WhCTEJ",
            required: true,
        }],
    label: (actor, items) => items.item.name,
    rows: (actor, items) => {
        return []
    },
    process: ({actor, rows, messages}) => {

    }
}
})

**Comment by reonZ** [comment]
The module doesn't interact with that item, do you have maybe a custom daily for it ?

**Comment by reonZ** [comment]
Closing this issue for lack of follow up
