### ISSUE TITLE
Flexible Studies

### ISSUE THREAD

**Issue by mereghost** [reonZ/pf2e-dailies#8]
Hi there,

First of all thanks for this nice module!
The `Flexible Studies` feat allows you to become trained in a skill of your choice for the day. `Lore` is a skill, basically allowing the player to select, besides untrained "normal" skills, they can become trained on a Lore.

PF2E System Source ID: `Compendium.pf2e.feats-srd.9bgl6qYWKHzqWZj0`

**Comment by reonZ** [comment]
With `1.15.0`, you are now able to enter the name of a lore skill whenever you have the option to select a skill.

![image](https://user-images.githubusercontent.com/651462/218319368-64f53ba3-0115-4c6c-bbf4-7d6424cc3149.png)
