### ISSUE TITLE
Talisman Esoterica not working with the module

### ISSUE THREAD

**Issue by Onestly7** [reonZ/pf2e-dailies#80]
With PF2e system version 6.6.1, thaumaturge with Talisman Esoterica can't temporarily craft the daily talismans through their crafting tab with Perform Daily Crafting, nor are the talisman craftings automated by this module in the daily preparation prompt.

In version 6.4.1 the Perform Daily Crafting at least gives affirmative comment, but no items are added to inventory with this module activated.

**Comment by reonZ** [comment]
Uploading Foundry_Virtual_Tabletop_06U8xqRxfF.mp4…

It works fine for me, are you up to date with the module ? Because there was an issue about daily crafting at one point but that was some time ago now.

**Comment by Onestly7** [comment]
Ah, that's probably it. The Forge version I'm using (build 328) version apparently won't let me get that update, and I'm stuck with earlier build of the module. Sorry for the bother.
