### ISSUE TITLE
Animist: Apparition spells should be signature

### ISSUE THREAD

**Issue by lholden** [reonZ/pf2e-dailies#86]
When generating the spell lists for the apparitions, it should mark them as signature.

> All your apparition spells are signature spells. That means that you can heighten any apparition spell freely by casting it from a higher-rank apparition spell slot, up to the maximum rank of apparition spell you can cast.

**Comment by reonZ** [comment]
https://github.com/reonZ/pf2e-dailies/wiki/Built%E2%80%90In-Dailies#apparition-attunement-animist
