### ISSUE TITLE
PF2e Dailies and HUD

### ISSUE THREAD

**Issue by GM-Swan** [reonZ/pf2e-dailies#91]
Any chance these 2 modules can be integrated??? It would be very nice if the prepare dailies and use of a magical staff could be used within Token Action HUD (so the character sheet doesn't have to be open).

**Comment by reonZ** [comment]
You are asking to the wrong person, the hud module should be the one integrating this, not the other way around.

Also, this is quite an ironic request considering i have my own HUD module and it does support this one.
